package com.android.universe.model.event

import kotlinx.serialization.Serializable

/**
 * Data Transfer Object (DTO) for events returned by the OpenAI API.
 *
 * This type represents only the raw AI-generated event data. It is intentionally smaller than the
 * app's internal `Event` model.
 *
 * The fields `id`, `creator`, `participants`, and `eventPicture` are not included here because they
 * are assigned later by the app during parsing and conversion.
 *
 * @property title name of the event.
 * @property description detailed information about the event.
 * @property date date and time when the event is scheduled to occur.
 * @property tags set of tags associated with the event for categorization.
 * @property location where the event will take place.
 */
@Serializable
data class EventDTO(
    val title: String,
    val description: String,
    val date: String, // "2025-04-12T20:00"
    val tags: List<String>,
    val location: LocationDTO,
)

/**
 * Data Transfer Object (DTO) representing a geographic location returned by the OpenAI API.
 *
 * This type contains only the raw latitude/longitude pair as generated by the model. Validation of
 * these coordinates (e.g., bounds checking) is performed later by `EventValidator` during parsing.
 *
 * Coordinate semantics:
 * - **latitude** must be within the range [-90.0, 90.0]
 * - **longitude** must be within the range [-180.0, 180.0]
 *
 * The app converts this DTO into its internal `Location` model after ensuring the values are valid.
 *
 * @property latitude north–south position, in degrees.
 * @property longitude east–west position, in degrees.
 */
@Serializable data class LocationDTO(val latitude: Double, val longitude: Double)
