package com.android.universe.model

import com.android.universe.model.CountryData.countryToIsoCode

/**
 * Provides static data related to countries and their ISO 3166-1 alpha-2 codes.
 *
 * This object contains:
 * - A list of all recognized country names [allCountries].
 * - A map associating each country name to its ISO 2-letter code [countryToIsoCode].
 *
 * It is primarily used to populate dropdowns or selection lists in UI forms, and to convert
 * user-friendly country names into standard ISO codes when storing user data.
 */
object CountryData {

  /**
   * List of all country names used for display purposes.
   *
   * This list is alphabetically ordered and includes most internationally recognized states. It can
   * be used to populate UI dropdowns menus or autocomplete suggestions.
   */
  val allCountries =
      listOf(
          "Afghanistan",
          "Albania",
          "Algeria",
          "Andorra",
          "Angola",
          "Antigua & Deps",
          "Argentina",
          "Armenia",
          "Australia",
          "Austria",
          "Azerbaijan",
          "Bahamas",
          "Bahrain",
          "Bangladesh",
          "Barbados",
          "Belarus",
          "Belgium",
          "Belize",
          "Benin",
          "Bhutan",
          "Bolivia",
          "Bosnia Herzegovina",
          "Botswana",
          "Brazil",
          "Brunei",
          "Bulgaria",
          "Burkina",
          "Burundi",
          "Cambodia",
          "Cameroon",
          "Canada",
          "Cape Verde",
          "Central African Rep",
          "Chad",
          "Chile",
          "China",
          "Colombia",
          "Comoros",
          "Congo",
          "Congo {Democratic Rep}",
          "Costa Rica",
          "Croatia",
          "Cuba",
          "Cyprus",
          "Czech Republic",
          "Denmark",
          "Djibouti",
          "Dominica",
          "Dominican Republic",
          "East Timor",
          "Ecuador",
          "Egypt",
          "El Salvador",
          "Equatorial Guinea",
          "Eritrea",
          "Estonia",
          "Ethiopia",
          "Fiji",
          "Finland",
          "France",
          "Gabon",
          "Gambia",
          "Georgia",
          "Germany",
          "Ghana",
          "Greece",
          "Grenada",
          "Guatemala",
          "Guinea",
          "Guinea-Bissau",
          "Guyana",
          "Haiti",
          "Honduras",
          "Hungary",
          "Iceland",
          "India",
          "Indonesia",
          "Iran",
          "Iraq",
          "Ireland {Republic}",
          "Israel",
          "Italy",
          "Ivory Coast",
          "Jamaica",
          "Japan",
          "Jordan",
          "Kazakhstan",
          "Kenya",
          "Kiribati",
          "Korea North",
          "Korea South",
          "Kosovo",
          "Kuwait",
          "Kyrgyzstan",
          "Laos",
          "Latvia",
          "Lebanon",
          "Lesotho",
          "Liberia",
          "Libya",
          "Liechtenstein",
          "Lithuania",
          "Luxembourg",
          "Macedonia",
          "Madagascar",
          "Malawi",
          "Malaysia",
          "Maldives",
          "Mali",
          "Malta",
          "Marshall Islands",
          "Mauritania",
          "Mauritius",
          "Mexico",
          "Micronesia",
          "Moldova",
          "Monaco",
          "Mongolia",
          "Montenegro",
          "Morocco",
          "Mozambique",
          "Myanmar, {Burma}",
          "Namibia",
          "Nauru",
          "Nepal",
          "Netherlands",
          "New Zealand",
          "Nicaragua",
          "Niger",
          "Nigeria",
          "Norway",
          "Oman",
          "Pakistan",
          "Palau",
          "Panama",
          "Papua New Guinea",
          "Paraguay",
          "Peru",
          "Philippines",
          "Poland",
          "Portugal",
          "Qatar",
          "Romania",
          "Russian Federation",
          "Rwanda",
          "St Kitts & Nevis",
          "St Lucia",
          "Saint Vincent & the Grenadines",
          "Samoa",
          "San Marino",
          "Sao Tome & Principe",
          "Saudi Arabia",
          "Senegal",
          "Serbia",
          "Seychelles",
          "Sierra Leone",
          "Singapore",
          "Slovakia",
          "Slovenia",
          "Solomon Islands",
          "Somalia",
          "South Africa",
          "South Sudan",
          "Spain",
          "Sri Lanka",
          "Sudan",
          "Suriname",
          "Swaziland",
          "Sweden",
          "Switzerland",
          "Syria",
          "Taiwan",
          "Tajikistan",
          "Tanzania",
          "Thailand",
          "Togo",
          "Tonga",
          "Trinidad & Tobago",
          "Tunisia",
          "Turkey",
          "Turkmenistan",
          "Tuvalu",
          "Uganda",
          "Ukraine",
          "United Arab Emirates",
          "United Kingdom",
          "United States",
          "Uruguay",
          "Uzbekistan",
          "Vanuatu",
          "Vatican City",
          "Venezuela",
          "Vietnam",
          "Yemen",
          "Zambia",
          "Zimbabwe")

  /**
   * Map linking each country name to its ISO 3166-1 alpha-2 code.
   *
   * This map is used for data normalization and backend interoperability.
   *
   * The map is case-sensitive and expects the exact name found in [allCountries].
   */
  val countryToIsoCode =
      mapOf(
          "Afghanistan" to "AF",
          "Albania" to "AL",
          "Algeria" to "DZ",
          "Andorra" to "AD",
          "Angola" to "AO",
          "Antigua & Deps" to "AG",
          "Argentina" to "AR",
          "Armenia" to "AM",
          "Australia" to "AU",
          "Austria" to "AT",
          "Azerbaijan" to "AZ",
          "Bahamas" to "BS",
          "Bahrain" to "BH",
          "Bangladesh" to "BD",
          "Barbados" to "BB",
          "Belarus" to "BY",
          "Belgium" to "BE",
          "Belize" to "BZ",
          "Benin" to "BJ",
          "Bhutan" to "BT",
          "Bolivia" to "BO",
          "Bosnia Herzegovina" to "BA",
          "Botswana" to "BW",
          "Brazil" to "BR",
          "Brunei" to "BN",
          "Bulgaria" to "BG",
          "Burkina" to "BF",
          "Burundi" to "BI",
          "Cambodia" to "KH",
          "Cameroon" to "CM",
          "Canada" to "CA",
          "Cape Verde" to "CV",
          "Central African Rep" to "CF",
          "Chad" to "TD",
          "Chile" to "CL",
          "China" to "CN",
          "Colombia" to "CO",
          "Comoros" to "KM",
          "Congo" to "CG",
          "Congo {Democratic Rep}" to "CD",
          "Costa Rica" to "CR",
          "Croatia" to "HR",
          "Cuba" to "CU",
          "Cyprus" to "CY",
          "Czech Republic" to "CZ",
          "Denmark" to "DK",
          "Djibouti" to "DJ",
          "Dominica" to "DM",
          "Dominican Republic" to "DO",
          "East Timor" to "TL",
          "Ecuador" to "EC",
          "Egypt" to "EG",
          "El Salvador" to "SV",
          "Equatorial Guinea" to "GQ",
          "Eritrea" to "ER",
          "Estonia" to "EE",
          "Ethiopia" to "ET",
          "Fiji" to "FJ",
          "Finland" to "FI",
          "France" to "FR",
          "Gabon" to "GA",
          "Gambia" to "GM",
          "Georgia" to "GE",
          "Germany" to "DE",
          "Ghana" to "GH",
          "Greece" to "GR",
          "Grenada" to "GD",
          "Guatemala" to "GT",
          "Guinea" to "GN",
          "Guinea-Bissau" to "GW",
          "Guyana" to "GY",
          "Haiti" to "HT",
          "Honduras" to "HN",
          "Hungary" to "HU",
          "Iceland" to "IS",
          "India" to "IN",
          "Indonesia" to "ID",
          "Iran" to "IR",
          "Iraq" to "IQ",
          "Ireland {Republic}" to "IE",
          "Israel" to "IL",
          "Italy" to "IT",
          "Ivory Coast" to "CI",
          "Jamaica" to "JM",
          "Japan" to "JP",
          "Jordan" to "JO",
          "Kazakhstan" to "KZ",
          "Kenya" to "KE",
          "Kiribati" to "KI",
          "Korea North" to "KP",
          "Korea South" to "KR",
          "Kosovo" to "XK",
          "Kuwait" to "KW",
          "Kyrgyzstan" to "KG",
          "Laos" to "LA",
          "Latvia" to "LV",
          "Lebanon" to "LB",
          "Lesotho" to "LS",
          "Liberia" to "LR",
          "Libya" to "LY",
          "Liechtenstein" to "LI",
          "Lithuania" to "LT",
          "Luxembourg" to "LU",
          "Macedonia" to "MK",
          "Madagascar" to "MG",
          "Malawi" to "MW",
          "Malaysia" to "MY",
          "Maldives" to "MV",
          "Mali" to "ML",
          "Malta" to "MT",
          "Marshall Islands" to "MH",
          "Mauritania" to "MR",
          "Mauritius" to "MU",
          "Mexico" to "MX",
          "Micronesia" to "FM",
          "Moldova" to "MD",
          "Monaco" to "MC",
          "Mongolia" to "MN",
          "Montenegro" to "ME",
          "Morocco" to "MA",
          "Mozambique" to "MZ",
          "Myanmar, {Burma}" to "MM",
          "Namibia" to "NA",
          "Nauru" to "NR",
          "Nepal" to "NP",
          "Netherlands" to "NL",
          "New Zealand" to "NZ",
          "Nicaragua" to "NI",
          "Niger" to "NE",
          "Nigeria" to "NG",
          "Norway" to "NO",
          "Oman" to "OM",
          "Pakistan" to "PK",
          "Palau" to "PW",
          "Panama" to "PA",
          "Papua New Guinea" to "PG",
          "Paraguay" to "PY",
          "Peru" to "PE",
          "Philippines" to "PH",
          "Poland" to "PL",
          "Portugal" to "PT",
          "Qatar" to "QA",
          "Romania" to "RO",
          "Russian Federation" to "RU",
          "Rwanda" to "RW",
          "St Kitts & Nevis" to "KN",
          "St Lucia" to "LC",
          "Saint Vincent & the Grenadines" to "VC",
          "Samoa" to "WS",
          "San Marino" to "SM",
          "Sao Tome & Principe" to "ST",
          "Saudi Arabia" to "SA",
          "Senegal" to "SN",
          "Serbia" to "RS",
          "Seychelles" to "SC",
          "Sierra Leone" to "SL",
          "Singapore" to "SG",
          "Slovakia" to "SK",
          "Slovenia" to "SI",
          "Solomon Islands" to "SB",
          "Somalia" to "SO",
          "South Africa" to "ZA",
          "South Sudan" to "SS",
          "Spain" to "ES",
          "Sri Lanka" to "LK",
          "Sudan" to "SD",
          "Suriname" to "SR",
          "Swaziland" to "SZ",
          "Sweden" to "SE",
          "Switzerland" to "CH",
          "Syria" to "SY",
          "Taiwan" to "TW",
          "Tajikistan" to "TJ",
          "Tanzania" to "TZ",
          "Thailand" to "TH",
          "Togo" to "TG",
          "Tonga" to "TO",
          "Trinidad & Tobago" to "TT",
          "Tunisia" to "TN",
          "Turkey" to "TR",
          "Turkmenistan" to "TM",
          "Tuvalu" to "TV",
          "Uganda" to "UG",
          "Ukraine" to "UA",
          "United Arab Emirates" to "AE",
          "United Kingdom" to "GB",
          "United States" to "US",
          "Uruguay" to "UY",
          "Uzbekistan" to "UZ",
          "Vanuatu" to "VU",
          "Vatican City" to "VA",
          "Venezuela" to "VE",
          "Vietnam" to "VN",
          "Yemen" to "YE",
          "Zambia" to "ZM",
          "Zimbabwe" to "ZW")
}

/** Reverse map for converting ISO codes back to human-readable names. */
val isoToCountryName = countryToIsoCode.entries.associate { (name, iso) -> iso to name }
