package com.android.universe.model

/**
 * Enumeration representing various tags that can be associated with user profiles.
 * Each tag has a [displayName] for user-friendly representation.
 */
enum class Tag(val displayName: String) {
  READING("Reading"),
  WRITING("Writing"),
  MUSIC("Music"),
  CINEMA("Cinema"),
  PHOTOGRAPHY("Photography"),
  VIDEO_GAMES("Video_Games"),
  PROGRAMMING("Programming"),
  ARTIFICIAL_INTELLIGENCE("Artificial intelligence"),
  ASTRONOMY("Astronomy"),
  ELECTRONICS("Electronics"),
  TRAVELING("Traveling"),
  COOKING("Cooking"),
  POLITICS("Politics"),
  PHILOSOPHY("Philosophy"),
  DRAWING("Drawing"),
  SCULPTURE("Sculpture"),
  POETRY("Poetry"),
  FASHION("Fashion"),
  BOARD_GAMES("Board games"),
  ROLE_PLAYING_GAMES("Role-playing games"),
  CAR_RACE("Car race"),
  RUNNING("Running"),
  FITNESS("Fitness"),
  SWIMMING("Swimming"),
  CYCLING("Cycling"),
  MOUNTAIN_BIKING("Mountain biking"),
  HIKING("Hiking"),
  YOGA("Yoga"),
  MEDITATION("Meditation"),
  PILATES("Pilates"),
  JUDO("Judo"),
  KARATE("Karate"),
  BOXING("Boxing"),
  FOOTBALL("Football"),
  BASKETBALL("Basketball"),
  VOLLEYBALL("Volleyball"),
  RUGBY("Rugby"),
  HANDBALL("Handball"),
  TENNIS("Tennis"),
  BADMINTON("Badminton"),
  TABLE_TENNIS("Table tennis"),
  SKIING("Skiing"),
  SNOWBOARDING("Snowboarding"),
  SKATING("Skating"),
  SURFING("Surfing"),
  GOLF("Golf"),
  KAYAKING("Kayaking"),
  DANCING("Dancing"),
  HORSEBACK_RIDING("Horseback riding"),
  JAZZ("Jazz"),
  POP("Pop"),
  ROCK("Rock"),
  RAP("Rap"),
  CLASSICAL("Classical"),
  BLUES("Blues"),
  METAL("Metal"),
  RNB("R&B"),
  FUNK("Funk"),
  REGGAE("Reggae"),
  ELECTRONIC("Electronic"),
  COUNTRY("Country"),
  INDIE("Indie"),
  PUNK("Punk"),
  K_POP("K_pop"),
  CAR("Car"),
  TRAIN("Train"),
  BOAT("Boat"),
  BUS("Bus"),
  BICYCLE("Bicycle"),
  FOOT("Foot"),
  PLANE("Plane"),
  AARGAU("Aargau"),
  APPENZELL_AUSSERRHODEN("Appenzell Ausserrhoden"),
  APPENZELL_INNERRHODEN("Appenzell Innerrhoden"),
  BASEL_LANDSCHAFT("Basel-Landschaft"),
  BASEL_STADT("Basel-Stadt"),
  BERN("Bern"),
  FRIBOURG("Fribourg"),
  GENEVA("Geneva"),
  GLARUS("Glarus"),
  GRAUBUNDEN("Graubünden"),
  JURA("Jura"),
  LUCERNE("Lucerne"),
  NEUCHATEL("Neuchâtel"),
  NIDWALDEN("Nidwalden"),
  OBWALDEN("Obwalden"),
  SCHAFFHAUSEN("Schaffhausen"),
  SCHWYZ("Schwyz"),
  SOLOTHURN("Solothurn"),
  ST_GALLEN("St. Gallen"),
  THURGAU("Thurgau"),
  TICINO("Ticino"),
  URI("Uri"),
  VALAIS("Valais"),
  VAUD("Vaud"),
  ZUG("Zug"),
  ZURICH("Zürich")
}

/**
 * List of tags related to interests.
 */
val tagsInterest =
    listOf(
        Tag.READING,
        Tag.WRITING,
        Tag.MUSIC,
        Tag.CINEMA,
        Tag.PHOTOGRAPHY,
        Tag.VIDEO_GAMES,
        Tag.PROGRAMMING,
        Tag.ARTIFICIAL_INTELLIGENCE,
        Tag.ASTRONOMY,
        Tag.ELECTRONICS,
        Tag.TRAVELING,
        Tag.COOKING,
        Tag.POLITICS,
        Tag.PHILOSOPHY,
        Tag.DRAWING,
        Tag.SCULPTURE,
        Tag.POETRY,
        Tag.FASHION,
        Tag.BOARD_GAMES,
        Tag.ROLE_PLAYING_GAMES,
        Tag.CAR_RACE)

/**
 * List of tags related to sports.
 */
val tagsSport =
    listOf(
        Tag.RUNNING,
        Tag.FITNESS,
        Tag.SWIMMING,
        Tag.CYCLING,
        Tag.MOUNTAIN_BIKING,
        Tag.HIKING,
        Tag.YOGA,
        Tag.MEDITATION,
        Tag.PILATES,
        Tag.JUDO,
        Tag.KARATE,
        Tag.BOXING,
        Tag.FOOTBALL,
        Tag.BASKETBALL,
        Tag.VOLLEYBALL,
        Tag.RUGBY,
        Tag.HANDBALL,
        Tag.TENNIS,
        Tag.BADMINTON,
        Tag.TABLE_TENNIS,
        Tag.SKIING,
        Tag.SNOWBOARDING,
        Tag.SKATING,
        Tag.SURFING,
        Tag.GOLF,
        Tag.KAYAKING,
        Tag.DANCING,
        Tag.HORSEBACK_RIDING)

/**
 * List of tags related to music.
 */
val tagsMusic =
    listOf(
        Tag.JAZZ,
        Tag.POP,
        Tag.ROCK,
        Tag.RAP,
        Tag.CLASSICAL,
        Tag.BLUES,
        Tag.METAL,
        Tag.RNB,
        Tag.FUNK,
        Tag.REGGAE,
        Tag.ELECTRONIC,
        Tag.COUNTRY,
        Tag.INDIE,
        Tag.PUNK,
        Tag.K_POP)

/**
 * List of tags related to transportation.
 */
val tagsTransport = listOf(Tag.CAR, Tag.TRAIN, Tag.BOAT, Tag.BUS, Tag.BICYCLE, Tag.FOOT, Tag.PLANE)

/**
 * List of tags related to Swiss cantons.
 */
val tagsCanton =
    listOf(
        Tag.AARGAU,
        Tag.APPENZELL_AUSSERRHODEN,
        Tag.APPENZELL_INNERRHODEN,
        Tag.BASEL_LANDSCHAFT,
        Tag.BASEL_STADT,
        Tag.BERN,
        Tag.FRIBOURG,
        Tag.GENEVA,
        Tag.GLARUS,
        Tag.GRAUBUNDEN,
        Tag.JURA,
        Tag.LUCERNE,
        Tag.NEUCHATEL,
        Tag.NIDWALDEN,
        Tag.OBWALDEN,
        Tag.SCHAFFHAUSEN,
        Tag.SCHWYZ,
        Tag.SOLOTHURN,
        Tag.ST_GALLEN,
        Tag.THURGAU,
        Tag.TICINO,
        Tag.URI,
        Tag.VALAIS,
        Tag.VAUD,
        Tag.ZUG,
        Tag.ZURICH)
